

using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using Serilog;
using Serilog.Events;
using Serilog.Formatting.Compact;
using Services.Auth.Application.IService;
using Services.Auth.Application.Mapper;
using Services.Auth.Application.Service;
using Services.Auth.Domain.Data;
using Services.Auth.Domain.Entities;
using Services.Auth.Domain.IRepositories;
using Services.Auth.Infrastructure.Cache;
using Services.Auth.Infrastructure.Configuration;
using Services.Auth.Infrastructure.Configuration.ExceptionHandlers;
using Services.Auth.Infrastructure.Extensions;
using Services.Auth.Infrastructure.Repositories;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// Set up logger 3rd party library
builder.Host.UseSerilog();

// Setting up serilog library
Log.Logger = new LoggerConfiguration()
               .Enrich.FromLogContext()
               .MinimumLevel.Override("Microsoft", LogEventLevel.Warning) // Don't log lower than warnings generated by the application
               .WriteTo.File(new CompactJsonFormatter(),
               builder.Configuration.GetValue<string>("LoggingLocation"),
               rollingInterval: RollingInterval.Day // Generates logs files in "log-yyyymmdd" format
               , retainedFileCountLimit: 90, // Keeps 90 days of log and delete it if older
               shared: true)
               .CreateLogger();

// Add services to the container.
builder.Services.AddDbContext<AppDbContext>(option =>
{
    option.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"));
});

builder.Services.AddIdentity<ApplicationUser, IdentityRole>().AddEntityFrameworkStores<AppDbContext>()
    .AddDefaultTokenProviders();

builder.Services.AddControllers();
builder.Services.AddMemoryCache();
builder.Services.AddHttpContextAccessor();

builder.Services.AddScoped<IUnitOfWork, UnitOfWork>();
builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<IOtpService, OtpService>();
builder.Services.AddScoped<ITokenService, TokenService>();
builder.Services.AddScoped<IUserService, UserService>();

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(swaggerOptions =>
{
    swaggerOptions.AddSecurityDefinition("Bearer",
        new OpenApiSecurityScheme
        {
            Description = "JWT Authorization header using the Bearer scheme (Example: 'Bearer 12345abcdef')",
            Name = "Authorization",
            In = ParameterLocation.Header,
            Type = SecuritySchemeType.ApiKey,
            Scheme = "Bearer"
        });

    swaggerOptions.AddSecurityRequirement(new OpenApiSecurityRequirement
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference
                        {
                            Type = ReferenceType.SecurityScheme,
                            Id = "Bearer"
                        }
                    },
                    Array.Empty<string>()
                }
            });
});





// Register AutoMapper
builder.Services.AddAutoMapper(cfg =>
{
    cfg.AddProfile<UserProfile>();
    cfg.AddProfile<TokenDetailsProfile>();
    cfg.AddProfile<OtpDetailsProfile>();
});
// Inject/Initialize static utilities
ConfigurationUtil.Initialize(builder.Configuration);

// Authorization JWT configuration
builder.AddAppAuthetication();

var app = builder.Build();

// Static utility initialization
CacheManager.Initialize(app.Services.GetRequiredService<IMemoryCache>());

// Configure global error handlers
app.UseMiddleware<MiddlewareExceptionHandler>();

// Configure the HTTP request pipeline.
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    if (!app.Environment.IsDevelopment())
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "auth API");
        c.RoutePrefix = string.Empty;
    }
});
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();



ApplyMigration();

app.Run();


void ApplyMigration()
{
    using (var scope = app.Services.CreateScope())
    {
        var _db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        if (_db.Database.GetPendingMigrations().Count() > 0)
        {
            _db.Database.Migrate();
        }
    }
}
