using System.Runtime.CompilerServices;


namespace Services.Email.Infrastructure.Configuration.ExceptionHandlers
{
    public class RestfulException : Exception
    {
        public int StatusCode { get; set; } // HTTP code
        public string? ErrorMessage { get; set; } // Description
        public string? TraceId { get; set; } // Trace id is auto generated by the global error middleware
        public string? FunctionName { get; set; } // Function where the error was thrown
        public string? ClassName { get; set; } // Function where the error was thrown
        public int? LineNumber { get; set; } // Function where the error was thrown

        public RestfulException() { }

        public RestfulException(string message, int statusCode, [CallerMemberName] string functionCallerName = "", [CallerFilePath] string callerFilePath = "", [CallerLineNumber] int callerLineNumber = 0)
        {
            StatusCode = statusCode;
            ErrorMessage = message;

            FunctionName = functionCallerName;
            ClassName = callerFilePath;
            LineNumber = callerLineNumber;
        }
    }
}
