using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using Serilog;
using Serilog.Events;
using Serilog.Formatting.Compact;
using Services.ServicesManagement.Application.IService.Lookups;
using Services.ServicesManagement.Application.IService.ServiceInfo;
using Services.ServicesManagement.Application.IService.ServiceStructure;
using Services.ServicesManagement.Application.Mapper;
using Services.ServicesManagement.Application.Service.Lookups;
using Services.ServicesManagement.Application.Service.ServiceInfo;
using Services.ServicesManagement.Application.Service.ServiceStructure;
using Services.ServicesManagement.Domain.DBContext;
using Services.ServicesManagement.Domain.IRepositories;
using Services.ServicesManagement.Infrastructure.Configuration;
using Services.ServicesManagement.Infrastructure.Configuration.ExceptionHandlers;
using Services.ServicesManagement.Infrastructure.Extensions;
using Services.ServicesManagement.Infrastructure.Repositories;

var builder = WebApplication.CreateBuilder(args);


// Set up logger 3rd party library
builder.Host.UseSerilog(Log.Logger);

// Setting up serilog library
Log.Logger = new LoggerConfiguration()
               .Enrich.FromLogContext()
               .MinimumLevel.Override("Microsoft", LogEventLevel.Warning) // Don't log lower than warnings generated by the application
               .WriteTo.File(new CompactJsonFormatter(),
               builder.Configuration.GetValue<string>("LoggingLocation"),
               rollingInterval: RollingInterval.Day // Generates logs files in "log-yyyymmdd" format
               , retainedFileCountLimit: 90, // Keeps 90 days of log and delete it if older
               shared: true)
               .CreateLogger();

// Add services to the container.
builder.Services.AddDbContext<ServicesManagementDbContext>(option =>
{
    option.UseSqlServer(
        builder.Configuration.GetConnectionString("DefaultConnection"),
        b =>
        {
            b.MigrationsAssembly("Services.ServicesManagement.Infrastructure");
        });

});

builder.Services.AddControllers();
builder.Services.AddMemoryCache();
builder.Services.AddHttpContextAccessor();


builder.Services.AddScoped<IUnitOfWork, UnitOfWork>();
builder.Services.AddScoped<IActivitiesService, ActivitiesService>();
builder.Services.AddScoped<IDocumentNameService, DocumentNameService>();
builder.Services.AddScoped<IDomainsService, DomainsService>();
builder.Services.AddScoped<IHeaderService, HeaderService>();
builder.Services.AddScoped<ITagsService, TagsService>();
builder.Services.AddScoped<IServiceInfoService, ServiceInfoService>();
builder.Services.AddScoped<IMainServiceService, MainServiceService>();
builder.Services.AddScoped<ISubServiceService, SubServiceService>();
builder.Services.AddScoped<ISubSubServiceService, SubSubServiceService>();




builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(swaggerOptions =>
{
    swaggerOptions.AddSecurityDefinition("Bearer",
        new OpenApiSecurityScheme
        {
            Description = "JWT Authorization header using the Bearer scheme (Example: 'Bearer 12345abcdef')",
            Name = "Authorization",
            In = ParameterLocation.Header,
            Type = SecuritySchemeType.ApiKey,
            Scheme = "Bearer"
        });

    swaggerOptions.AddSecurityRequirement(new OpenApiSecurityRequirement
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference
                        {
                            Type = ReferenceType.SecurityScheme,
                            Id = "Bearer"
                        }
                    },
                    Array.Empty<string>()
                }
            });
});


// Register AutoMapper
builder.Services.AddAutoMapper(cfg =>
{
    cfg.AddProfile<ActivitiesProfile>();
    cfg.AddProfile<DocumentNameProfile>();
    cfg.AddProfile<DomainsProfile>();
    cfg.AddProfile<HeaderProfile>();
    cfg.AddProfile<MainServiceProfile>();
    cfg.AddProfile<PaginationParametersProfile>();
    cfg.AddProfile<ServiceInfoProfile>();
    cfg.AddProfile<SubServiceProfile>();
    cfg.AddProfile<SubSubServiceProfile>();
    cfg.AddProfile<TagsProfile>();
    cfg.AddProfile<DocumentValueProfile>();
    cfg.AddProfile<HeaderValueProfile>();

});



// Inject/Initialize static utilities
ConfigurationUtil.Initialize(builder.Configuration);

// Authorization JWT configuration
builder.AddAppAuthetication();


var app = builder.Build();




// Configure global error handlers
app.UseMiddleware<MiddlewareExceptionHandler>();
// Configure the HTTP request pipeline.
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    if (!app.Environment.IsDevelopment())
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "auth API");
        c.RoutePrefix = string.Empty;
    }
});
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();



ApplyMigration();

app.Run();


void ApplyMigration()
{
    using (var scope = app.Services.CreateScope())
    {
        var _db = scope.ServiceProvider.GetRequiredService<ServicesManagementDbContext>();

        if (_db.Database.GetPendingMigrations().Count() > 0)
        {
            _db.Database.Migrate();
        }
    }
}