using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using Serilog;
using Serilog.Events;
using Serilog.Formatting.Compact;
using Services.FileManagement.Application.IService;
using Services.FileManagement.Application.Job;
using Services.FileManagement.Application.Mapper;
using Services.FileManagement.Application.Service;
using Services.FileManagement.Domain.DBContext;
using Services.FileManagement.Domain.IRepositories;
using Services.FileManagement.Infrastructure.Configuration;
using Services.FileManagement.Infrastructure.Configuration.ExceptionHandlers;
using Services.FileManagement.Infrastructure.Extensions;
using Services.FileManagement.Infrastructure.Repositories;

var builder = WebApplication.CreateBuilder(args);


// Set up logger 3rd party library
builder.Host.UseSerilog(Log.Logger);

// Setting up serilog library
Log.Logger = new LoggerConfiguration()
               .Enrich.FromLogContext()
               .MinimumLevel.Override("Microsoft", LogEventLevel.Warning) // Don't log lower than warnings generated by the application
               .WriteTo.File(new CompactJsonFormatter(),
               builder.Configuration.GetValue<string>("LoggingLocation"),
               rollingInterval: RollingInterval.Day // Generates logs files in "log-yyyymmdd" format
               , retainedFileCountLimit: 90, // Keeps 90 days of log and delete it if older
               shared: true)
               .CreateLogger();

// Add services to the container.
builder.Services.AddDbContext<FileManagementDbContext>(option =>
{
    option.UseSqlServer(
      builder.Configuration.GetConnectionString("DefaultConnection"),
      b =>
      {
          b.MigrationsAssembly("Services.FileManagement.Infrastructure");
      });
});

builder.Services.AddControllers();
builder.Services.AddMemoryCache();
builder.Services.AddHttpContextAccessor();

builder.Services.AddScoped<IUnitOfWork, UnitOfWork>();
builder.Services.AddScoped<IDownloadService, DownloadService>();
builder.Services.AddScoped<IUploadService, UploadService>();



builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(swaggerOptions =>
{
    swaggerOptions.AddSecurityDefinition("Bearer",
        new OpenApiSecurityScheme
        {
            Description = "JWT Authorization header using the Bearer scheme (Example: 'Bearer 12345abcdef')",
            Name = "Authorization",
            In = ParameterLocation.Header,
            Type = SecuritySchemeType.ApiKey,
            Scheme = "Bearer"
        });

    swaggerOptions.AddSecurityRequirement(new OpenApiSecurityRequirement
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference
                        {
                            Type = ReferenceType.SecurityScheme,
                            Id = "Bearer"
                        }
                    },
                    Array.Empty<string>()
                }
            });
});


// Register AutoMapper
builder.Services.AddAutoMapper(cfg =>
{
    cfg.AddProfile<MediaFileProfile>();

});

builder.Services.AddSingleton<UploadFileJob>();
builder.Services.AddHostedService(provider => provider.GetRequiredService<UploadFileJob>());

builder.Services.AddHostedService<ScheduledUploadFileJob>();


// Inject/Initialize static utilities
ConfigurationUtil.Initialize(builder.Configuration);

// Authorization JWT configuration
builder.AddAppAuthetication();


var app = builder.Build();


// Configure global error handlers
app.UseMiddleware<MiddlewareExceptionHandler>();
// Configure the HTTP request pipeline.
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    if (!app.Environment.IsDevelopment())
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "auth API");
        c.RoutePrefix = string.Empty;
    }
});
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();



ApplyMigration();

app.Run();


void ApplyMigration()
{
    using (var scope = app.Services.CreateScope())
    {
        var _db = scope.ServiceProvider.GetRequiredService<FileManagementDbContext>();

        if (_db.Database.GetPendingMigrations().Count() > 0)
        {
            _db.Database.Migrate();
        }
    }
}